Update website deployment
ashokirla/Fabrikam pull request #121
Opened 2022-03-10 08:30 UTC by ashokirla

2022-03-10 08:42 UTC, ifeilder commented
@ashokirla Does this PR handle all the homepage test cases

2022-10-13 13:55 UTC, JannesPeters requested changes

2022-10-13 13:55 UTC, JannesPeters commented on .github/workflows/ABC.yml
>      # Steps represent a sequence of tasks that will be executed as part of the job
ASDAS

2022-10-13 13:55 UTC, JannesPeters commented on .github/workflows/ABC.yml
> +    environment: Test
ASDAS

2022-10-13 13:55 UTC, JannesPeters commented on .github/workflows/ABC.yml
>    build:
ASDASDASD

2022-11-21 09:47 UTC, ashokirla commented
New comment1234

2022-11-21 09:47 UTC, ashokirla commented
Comment12345

2022-11-21 09:51 UTC, closed without merging